### ISSUE TITLE
Meetup: Generators and Koa

### ISSUE THREAD

**Issue by nizaroni** [SunshineJS/undefined#1]
Generators and [Koa](http://koajs.com/) with special guest @elbuo8.

@elbuo8 will be visiting Miami from Tuesday July 29th to Friday August 1st so we are trying to set up a meetup during that time. @onel0p3z let's run it by the PwC guys to see if we can secure the space for one of those days. Do you know their GitHub usernames so we can pull them in here?

**Comment by onel0p3z** [comment]
@khalifenizar can't think of any ... checking :+1:

**Comment by elbuo8** [comment]
Let me know however I can help.

cc: @heydluv

**Comment by nizaroni** [comment]
Sent an email to Carlos and Paul from PwC. Hopefully they will weigh in soon!

**Comment by onel0p3z** [comment]
@khalifenizar :thumbsup:

**Comment by heydluv** [comment]
I can cross-promote with API-Craft Miami. Please keep me posted.

**Comment by nizaroni** [comment]
@elbuo8 PwC has okayed Tuesday the 29th. What's your flight itinerary? Does it allow the meetup to be on Tuesday?

**Comment by elbuo8** [comment]
Worst day possible but go for it.

On Wednesday, July 23, 2014, Nizar Khalife Iglesias <
notifications@github.com> wrote:

> @elbuo8 https://github.com/elbuo8 PwC has okayed Tuesday the 29th.
> What's your flight itinerary? Does it allow the meetup to be on Tuesday?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/khalifenizar/MiamiJS/issues/1#issuecomment-49877057.

## 

Yamil Asusta
@elbuo8 https://twitter.com/elbuo8

**Comment by nizaroni** [comment]
Let's try for Wednesday or Thursday then! Will let you know.

**Comment by nizaroni** [comment]
Sent a note to Carlos from PwC requesting a date change.

@elbuo8 We spoke about food and beverage sponsorship but I'd love to get that "on the record" if you don't mind. :P

BTW I can provide a ride on the day of (once we finalize the date).

**Comment by elbuo8** [comment]
Food and beer brah.

On Wednesday, July 23, 2014, Nizar Khalife Iglesias <
notifications@github.com> wrote:

> Sent a note to Carlos from PwC requesting a date change.
> 
> @elbuo8 https://github.com/elbuo8 We spoke about food and beverage
> sponsorship but I'd love to get that "on the record" if you don't mind. :P
> 
> BTW I can provide a ride on the day of (once we finalize the date).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/khalifenizar/MiamiJS/issues/1#issuecomment-49897378.

## 

Yamil Asusta
@elbuo8 https://twitter.com/elbuo8

**Comment by nizaroni** [comment]
Carlos said he would check for the date change in the morning as he is out of the office. He mentioned it would likely be Thursday.

**Comment by onel0p3z** [comment]
:+1: awesome guys !! Thank you @khalifenizar @elbuo8

**Comment by nizaroni** [comment]
We are confirmed for Thursday the 31st at 7pm! Creating the event in meetup.com now!

**Comment by nizaroni** [comment]
Boom! http://www.meetup.com/NodeJS-Enthusiasts-SE-Florida/events/197037062/

**Comment by nizaroni** [comment]
We've hit a bit of a road block: looks like PwC won't be able to provide us their space that day after all. We are trying to find a replacement venue. If that fails we might be forced to change the date to Wednesday the 30th. We will try to avoid doing that if possible though.

**Comment by elbuo8** [comment]
Cool

On Monday, July 28, 2014, Nizar Khalife Iglesias notifications@github.com
wrote:

> We've hit a bit of a road block: looks like PwC won't be able to provide
> us their space that day after all. We are trying to find a replacement
> venue. If that fails we might be forced to change the date to Wednesday the
> 30th. We will try to avoid doing that if possible though.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/khalifenizar/MiamiJS/issues/1#issuecomment-50359809.

## 

Yamil Asusta
@elbuo8 https://twitter.com/elbuo8

**Comment by nizaroni** [comment]
Ranger Technical was nice enough to provide us their offices in Fort Lauderdale for our meetup. Will update as soon as I confirm the address.

**Comment by nizaroni** [comment]
New address:

> Ranger Technical
> 805 E. Broward Blvd.
> Suite 200
> Fort Lauderdale, FL 33301

Hopefully it won't turn off too many attendees. :(

Updated the meetup event: http://www.meetup.com/NodeJS-Enthusiasts-SE-Florida/events/197037062/.

**Comment by elbuo8** [comment]
@heydluv mind sharing some love? :)

**Comment by onel0p3z** [comment]
:+1: See you all !!! :D

**Comment by heydluv** [comment]
Nice! I'm going to cross-promote on API-Craft meetup.

**Comment by nizaroni** [comment]
Plan for tomorrow: @elbuo8 will meet me at my office in Midtown at 5pm-ish. We will purchase the beers and set off around 5:30pm to compensate for traffic. On the way we will arrange for food delivery.

**Comment by nizaroni** [comment]
**BOOM!** First issue done! :godmode:

**Comment by nizaroni** [comment]
@elbuo8 Thanks a million for your talk and your sponsorship! I'd love to have you back when you are in town again! Let me know if you haven't gone 100% Go by then! :fist:

**Comment by onel0p3z** [comment]
@khalifenizar :dancers: <3 much love and respect @elbuo8 !!! ps: plz don't do the TJ :100:%

**Comment by elbuo8** [comment]
Anytime guys :)
