### ISSUE TITLE
Miami Node.JS Meetup: Loopback Framework - September 25th (?)

### ISSUE THREAD

**Issue by luccastera** [SunshineJS/undefined#11]
Not sure if this is the best way to make sure we don't schedule meetups at the same time.

I have everything ready for the September meetup: space + speaker.

The speaker will be someone from StrongLoop http://strongloop.com/ presenting via Hangout and talking about the Loopback framework (http://loopback.io/). We will hold it at the Group Office Space in Brickell.

I'm ready to schedule everything on meetup but wanted to check for conflicts with you guys first. I checked on Meetup.com and didn't see anything of interest that would conflict with it.

**Comment by nizaroni** [comment]
We don't have anything scheduled for September yet so feel free to create the event!

I'm watching the repo so any issue you create will ping me on GitHub. As dates become more solid, we usually make comments in the meetup's issue. If need be we can always @-mention each other to confirm that there are no conflicts.

**Comment by nizaroni** [comment]
This was a good one!
