### ISSUE TITLE
Meetup: Node Buffers, Performance, and Image Glitching

### ISSUE THREAD

**Issue by nizaroni** [SunshineJS/undefined#13]
As per [our short Twitter conversation](https://twitter.com/khalifenizar/status/524739293903085568), @brycebaril has agreed to be beamed in all the way from Seattle for our November meetup! As soon as we confirm a convenient date (or range thereof), I'll make arrangements for our physical venue.

**Comment by onel0p3z** [comment]
OMG OMG OMG so looking forward to this :heart:

**Comment by nizaroni** [comment]
@brycebaril How is your schedule looking on Monday the 17th, Monday the 24th, Tuesday the 25th or Wednesday the 26th? The meetup would be at 7:00-7:30pm EST. I believe that's 4:00-4:30pm in Seattle.

Would you like some help in coming up with a topic?

**Comment by brycebaril** [comment]
This month is finally solidifying for me --

Looks like 11/24 or 11/25 are the best two options, followed by 11/26

As for a topic, I'm thinking I'd love to do:

**Node Buffers, Performance, and Image Glitching** -- A case study of Node performance optimization with the image glitching done by http://revisit.link. 

How long are you thinking for the talk?

**Comment by nizaroni** [comment]
@brycebaril Oooooh that should be cool! I'm flexible on the duration. I don't run a timer when I speak but I think I've done no more than an hour.

I'll push for the 24th or 25th. Will let you know when I talk to the venue.

@onel0p3z Today I met with the Tim Hasse, the co-founder of [General Provision](https://twitter.com/GenProvision), a coworking space in Fort Lauderdale. I think it would be a great venue for us. Will talk to him about the dates in question this week.

**Comment by davenotik** [comment]
I love this use of GitHub. :) (Consider also posting on http://woven.co, and folks who get the daily email digest (http://eepurl.com/7HnnX) will see it as well.)

**Comment by onel0p3z** [comment]
@davenotik +1

**Comment by nizaroni** [comment]
We are confirmed for Monday, November 24th at 7:30 p.m. EST, 4:30 p.m. PST! I've created [the event on Meetup](http://www.meetup.com/NodeJS-Enthusiasts-SE-Florida/events/218697836).

@brycebaril I Internet stalked you a little bit for the blurb about you in the description. If you want to modify it in any way, please let me know. I am tolerant of nitpicks, being a nitpicker myself. Congrats on joining NodeSource, by the way! That had escaped my attention.

If you wouldn't mind, I would love to have a pre-meetup Hangout with you the day (or the Friday) before the event. Send me a Twitter direct message with your Hangout email whenever you get the chance.

I'm also thinking of streaming the Hangout and publishing it on YouTube. Any objections to that?

**Comment by nizaroni** [comment]
Boom! That was awesome. Thanks, @brycebaril. Feel free to send me any feedback about the experience from the remote speaker perspective.

For posterity, here are the links to the slides and the YouTube video (video trimming in progress):
- [Bryce's slides](http://brycebaril.github.io/glitch-perf-talk)
- [YouTube video of the talk](https://www.youtube.com/watch?v=-MCnBvDSoB0)
