### ISSUE TITLE
Meetup: @buritica 

### ISSUE THREAD

**Issue by onel0p3z** [SunshineJS/undefined#2]
We have the honor and privilege to have Juan Pablo Buritica @buritica talk to us.

**Topic:** TBA
**Date:** 2nd week of September

**Comment by nizaroni** [comment]
I was about to make this. :P :+1:

@Buritica thanks! Please let us know as about your travel plans and what sort of weird and wacky Node.js and JavaScript stuff you've been into lately that you'd like to talk about!

**Comment by montogeek** [comment]
This meetups has live stream or at least some kind of recorded video? Thanks :)

**Comment by buritica** [comment]
Hey guys, let me figure it out. I have a delivery on Sept 1st so my availability depends greatly on this. As far as subject's, is there anything interesting people in MIA have been asking about, I'd like to talk about something that's not the usual Intro to Node or shit.

**Comment by nizaroni** [comment]
@Buritica No problem! We will figure out the timing as things develop. We can keep the issue open until it works out for everybody!

I think the best talks are a result of the speaker's passion for the subject. I'd hate for you to speak about something you are bored with. What cool Node.js or JavaScript things have you learned about or tinkered with recently? What is holding your interest right now? What is inspiring you to Node lately? I'd love for you to speak about that! (I should probably write a blog post or something about this)

If you need to narrow it down I'd be glad to help. We haven't covered many topics yet so almost anything is on the table. I have a few requests from the community if you need something to kickstart your thought process. Let me know and I'll post them!

@montogeek I think streaming and recording would be a really cool thing to do. I'm not sure how soon we can start doing it, bit it's definitely on my logistics wishlist!

**Comment by onel0p3z** [comment]
@Buritica :D any plans for a SoFLo stop in December '14 or January '15 ? looking forward to have you as speaker in our meetup :+1:

**Comment by buritica** [comment]
Going to be in Colombia in those dates, but I think I’m coming down to FL in Feb or March. I have that pending and will make it happen.

—
Juan Pablo Buritica
t: @buritica

**Comment by onel0p3z** [comment]
Greatly appreciated Sir !!
