### ISSUE TITLE
Joint meetup with API Craft  - API Testing with Frisby.js

### ISSUE THREAD

**Issue by onel0p3z** [SunshineJS/undefined#3]
@heydluv offered to do a joint meetup in **August**. Let's use this issue to plan and get this going <3. @khalifenizar plz lmk what you think :+1:

**Comment by nizaroni** [comment]
Sounds good! I know nothing about Frisby.js so I'd love to hear a talk about it!

**Comment by heydluv** [comment]
Excellent. I know it will be a good topic from a good source! I'm planning for August 14 at 7pm somewhere in FLL, since our speaker cannot make it down to Miami on time. I have a contact at a new coworking place in FLL called Axis Space http://axisspace.com/ Do you guys have any recommendations? Let's make it a fun! SendGrid will sponsor the Beer and I'll find another to sponsor the Chipotle.

**Comment by nizaroni** [comment]
I can contact Johnathon Jadvani from Ranger Technical. Its through him that the company sponsors Data Masters. I believe they have an office in FLL with a small conference that we might be able to use if it's not a massive affair. What do you expect for attendance?

**Comment by heydluv** [comment]
Last time we had 40 in attendance. So, I'd say more or less the same turn out.

**Comment by nizaroni** [comment]
In that case I'd say that Ranger Technical probably won't work. I think I'll contact him anyway to see if he has any ideas though. :(

Hey, this is a happy problem to have.

**Comment by nizaroni** [comment]
@heydluv I spoke to the guys at Ranger Tech and they indicated that they have some contacts at [Nova Southeastern University](http://www.nova.edu/) that they can connect us to. As the Ranger guys tell it, Nova is very enthusiastic about fostering the local tech community and have access to larger spaces (some that can fit 50 people, others even larger than that). I'll send the Ranger guys an email tomorrow copying errbody to officially ask for the Nova contacts.

**Comment by onel0p3z** [comment]
@heydluv I'm sorry I totally blanked on this one: The _original_ creator and organizer of the NodeJS meetup "Stuart Malin" hosted initial meetups at NSU and I think he is part of faculty. He'll be at the meetup today so I'll introduce you to him :+1:

**Comment by heydluv** [comment]
@khalifenizar @onel0p3z I haven't had much luck in getting through to Nova or Axis Space. Seeing as there are very few RSVPs (probably bcz no location is set), I say we do the meetup at Ranger Tech again. I just reached out to Devon, but I'm sure it's gonna be OK.

**Comment by nizaroni** [comment]
Sounds good. I should probably attend more meetups in Fort Lauderdale to find some other tech companies up there.

**Comment by onel0p3z** [comment]
Ok @heydluv please provide link so we can create the meetup :D

**Comment by heydluv** [comment]
@onel0p3z I just announced it to my meetup. Didn't realize I hadn't announced it yet! lol. Here's the link. Thanks! http://www.meetup.com/API-Craft-Miami/events/188482082/
