### ISSUE TITLE
Meetup: Streams and `stream-adventure`

### ISSUE THREAD

**Issue by nizaroni** [SunshineJS/undefined#4]
Introduction to streams and [`stream-adventure`](https://www.npmjs.org/package/stream-adventure). I think this should be a two-part meetup. The first should be a regular talk about streams with a little time to hack on `stream-adventure`. Then we should do a second part in the weekend to hack on `stream-adventure` for a longer period of time.

**Comment by nizaroni** [comment]
I sent an email to Carlos from PwC to see if we can get these puppies hosted in the beginning of October.

Also I thought of a name for weekend free-form sessions: `Weekend Wizardry`.

**Comment by nizaroni** [comment]
I'm now trying to schedule this for the week before [{FinTank}](http://thefintank.com/) so that we can have the Weekend Wizardry session there.

**Comment by nizaroni** [comment]
Got [Ranger](http://rangertech.com/) to provide us our venue and sponsor food and beverages! I've created the [meetup event](http://www.meetup.com/NodeJS-Enthusiasts-SE-Florida/events/211272132/). Weekend Wizardry session pending. Brian from Ranger is putting me in contact with the {FinTank} people.

**Comment by onel0p3z** [comment]
:dancers: :dancer:

**Comment by nizaroni** [comment]
Secured a space at FinTank. Confirming the details to create the event.

**Comment by nizaroni** [comment]
Meetup event: http://www.meetup.com/NodeJS-Enthusiasts-SE-Florida/events/215114182/. It's pretty short notice so we will see if anybody shows up.

**Comment by nizaroni** [comment]
Boom! Didn't go half bad!
